---
- name: Tap all
  community.general.homebrew_tap:
    name: "{{ item.tap }}"
  loop: "{{ formula }}"
  when: item.tap is defined

- name: Ensure installed formula
  community.general.homebrew:
    name: "{{ item.name }}"
    state: present
  loop: "{{ formula }}"
