---
- name: Ensure host configuration directory exists
  file:
    path: "{{ host_config_path }}"
    state: directory

- name: Ensure host home directory exists
  file:
    path: "{{ host_home_path }}"
    state: directory

- name: Link dotfiles config to host config
  shell: |
    for item in $(find {{ dotfiles_config_path }} -mindepth 1 -maxdepth 1); do
      basename=$(basename "$item")
      target="{{ host_config_path }}/$basename"
      if [ ! -e "$target" ] || [ "$(readlink "$target")" != "$item" ]; then
        ln -sfn "$item" "$target"
      fi
    done
  args:
    executable: /bin/bash

- name: Link dotfiles home to host home
  shell: |
    for item in $(find {{ dotfiles_home_path }} -mindepth 1 -maxdepth 1); do
      basename=$(basename "$item")
      target="{{ host_home_path }}/$basename"
      if [ ! -e "$target" ] || [ "$(readlink "$target")" != "$item" ]; then
        ln -sfn "$item" "$target"
      fi
    done
  args:
    executable: /bin/bash
