---
- name: update homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Tap all
  community.general.homebrew_tap:
    name: "{{ item.tap }}"
  loop: "{{ formula }}"
  when: item.tap is defined

- name: Ensure installed formula
  community.general.homebrew:
    name: "{{ item.name }}"
    state: present
  loop: "{{ formula }}"
  when: item.cask is not defined

- name: Ensure installed cask
  community.general.homebrew_cask:
    name: "{{ item.cask }}"
    state: present
  loop: "{{ formula }}"
  when: item.cask is defined

- name: update all packages
  community.general.homebrew:
    upgrade_all: true
