return {
	require("plugins.which-key"),
	require("plugins.cpm"),
	require("plugins.neo-tree"),
	require("plugins.web-devicons"),
	require("plugins.conform"),
	require("plugins.todo-comments"),
	require("plugins.tokyonight"),
	require("plugins.mini"),
	require("plugins.lualine"),
	require("plugins.barbecue"),
	require("plugins.tmux-navigation"),
	require("plugins.telescope"),
	require("plugins.lsp"),
}
