---
- name: Set Key Repeat Rate
  shell: |
    defaults write -g InitialKeyRepeat -int 15 # normal minimum is 15 (225 ms)
    defaults write -g KeyRepeat -int 2 # normal minimum is 2 (30 ms)
  args:
    executable: /bin/bash
- name: Disable Natural Scrolling
  shell: |
    defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false
  args:
    executable: /bin/bash
- name: Auto Hide Dock
  shell: |
    defaults write com.apple.dock autohide -bool true
    defaults write com.apple.dock autohide-delay -float 0
    defaults write com.apple.dock autohide-time-modifier -float 0
  args:
    executable: /bin/bash
- name: Enable key autorepeat
  shell: |
    defaults write -g ApplePressAndHoldEnabled -bool false
  args:
    executable: /bin/bash
